// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQc9L5F-XfcOCFGsumBwCr7os0KgAtBT8',
    appId: '1:935264185763:web:813ef8b942e50dcda7be16',
    messagingSenderId: '935264185763',
    projectId: 'test-flutter-app-ea100',
    authDomain: 'test-flutter-app-ea100.firebaseapp.com',
    storageBucket: 'test-flutter-app-ea100.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxmvd3wVJHQD7l-Dione0xBR6izADkAWM',
    appId: '1:935264185763:android:c9373e09110f60cca7be16',
    messagingSenderId: '935264185763',
    projectId: 'test-flutter-app-ea100',
    storageBucket: 'test-flutter-app-ea100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Meo7EV_unt967eDenidQGa6zDKf0BPs',
    appId: '1:935264185763:ios:9e95a68fd95448bda7be16',
    messagingSenderId: '935264185763',
    projectId: 'test-flutter-app-ea100',
    storageBucket: 'test-flutter-app-ea100.appspot.com',
    iosClientId:
        '935264185763-pjsjj11734plccng8ksfrf855143mooc.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
