name: pipeline
on:
 push: 
  branches:
    - main
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - run: npm install -g firebase-tools
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          architecture: x64
      - run: |
          ls
          cd hello_world 
          flutter pub get
          flutter test
          flutter build web
          flutter build appbundle
          cd build
          ls


        
