name: pipeline
on:
 push: 
  branches:
    - main

defaults:
      run:
       working-directory: ./hello_world
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
      - run: flutter build ios --release --no-codesign
        
