name: pipeline
on:
 push: 
  branches:
    - main

permissions:
  issues: write
  contents: write
  packages: write
  repository-projects: write

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - run: npm install -g firebase-tools
      - uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          architecture: x64
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '{
  "type": "service_account",
  "project_id": "test-flutter-app-ea100",
  "private_key_id": "18c29e7ad948cf5f6abadae8158d5f27d88b9a3f",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/AkTDKUWS1hio\ncItsl4YM4BODAYW7/HUvP6SL1MktRpxS0kjWWnOVoWjmqtlYSCZUZaVPqnP+YnIp\nuGXEAlQAU9px5Vji+qug6MxOLd8fGjKQPBVd9E9fazssz5DZXHzX19EaQjt1i7FY\nK6hZEnM7XdmTbtv6F2EsF0RI7JMLTfn+0Q3OXtwJwRDFz1qnltUvokIf7kuwIA34\nRiqX5kOs7wPmda4BfF0u+SJihQ34KW+rOZ8dJe9JaDV12WpbPudcTtNocxnxLDPK\nW+dxvvBqrmHDLM1Qjw10/W3oVwfd+01gVDIn1ras/Wa7Oju9MZLwiUsiu5veq0j/\noUY9FOUnAgMBAAECggEAXieuoKtsDc02u3U67S0mGZutUpNCCqAQXdmX8YvTHVvk\nvBjHac6NknFN5gLK/68VId43JnWmFvwNPY6Vr5DcOosbL7C3569cQgXvjAwlo83E\npf/QIo/HPoh704N/6f2i1r0eaLzEVZWmNonSwxGKtvV0xq3LhtTWhCb19KKVe2i7\nF6zQxelDg/KaJZlyXxkzlHAZIJX1O8LrPRMfGpUB7hHw1JL7/WApODbprl/hEzWU\nQ5rVbxjVq/bXuX2uzBPSybQiD7qNvduCeuqW1vJYsv3W6DUCTfc2QWeZghQ3r5am\nUGprBk31PQZGRn3JgHkYBlWjHbEki1Xm3CHeLcqblQKBgQDkVcboA3vl+wLWNLW8\nGYH7N78G5IcG8YxelXTDeDZIREs9RPLnpJa0e3jpyjx708fXP/piMTqXVWv/4SuS\nR4UcDRfUEchivX9PodcLdh/3kllFTequ3WkBgS796g2QByxE9J570tkl0tZVQKuM\nBwZ3xhZEG4wFFfNH9TTFK7PnvQKBgQDWJsCRBua82Z0FY4zY9wr132+GBEDTMt2Q\nVJ5gZPcUR1i8sZMwi9kAyAIN7YqCf64tLmYujymmjF/OEf/YzNFXqk5K+0M3SanW\ncyJTcTBoDHdolj11lw/HC5esScrWwy5xW7+TFjGzJBUsN6PE5zgmTNLokntjMVkq\n+uTvmXEMswKBgQCG8BIuRvDPhrm0cU39LW3dUqJ3plINzm3P768jXUVnC8UTHk4W\nivPtERLxxuxbmVp+YHbN1J31lSvP+ffP6KhHXY15bFDp2WcFXnVBdruJiVlsVZGd\naYeGthtZPxpoxXRqA84tCvv9GE5F74Pxqq0t10iNU2I6FzDAk65t31fgWQKBgDPt\nE5ZW2Q4DqipLWDSnulWiBvW1BE7xr322tuxirvKQ1jhyymDkGAszdCQSbBp2gTJd\nZNN3TT8gHH7oKGRWTZB3MCLISCUYzIC+TB11fapNE4sdmutvZJj7+5wADJoEm7dK\n6unsYMKyRhwBpckx05Cd4ioYkqibp6ZfTbG3QA03AoGBAM44tTbP1z/kqeHPoCK1\neY2Wkos6F3fzY6vLn2jDXb3mIL0Gi+o0ASJm+TCwKQIK/8aGMj8xD7cq0VwtmyWs\nOh5uJr8sMr+A++n4mkKcHDUbF0kCImv6oZqsj/GmGV+WtzUBlHkiuFLVpCUOsfPV\nfCxniWPShBTKcRMhJGIz3qw7\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-5h11g@test-flutter-app-ea100.iam.gserviceaccount.com",
  "client_id": "115817296011922823954",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-5h11g%40test-flutter-app-ea100.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'
      - run: |
          cd hello_world 
           echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
          flutter pub get
          flutter build appbundle
          firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab --debug --app "1:935264185763:android:c9373e09110f60cca7be16" --token "1//03K3eO7v7-fAnCgYIARAAGAMSNwF-L9IrYFixhx7UGwjiTmZjmd4_XcfMe9-DARDiiBre2szIBi3Xjr4GdbkNbHp1zfe2o1_3Ehs"
      # - name: Install semantic
      #   run: |
      #     npm i semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/github @semantic-release/git @semantic-release/release-notes-generator semantic-release-slack-bot @commitlint/cli @commitlint/config-conventional
      # - name: Run semantic
      #   id: release
      #   run: |
      #     npx semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Do something when a new release published
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: |
      #    echo ${{ steps.semantic.outputs.new_release_version }}
      #    echo ${{ steps.semantic.outputs.new_release_major_version }}
      #    echo ${{ steps.semantic.outputs.new_release_minor_version }}
      #    echo ${{ steps.semantic.outputs.new_release_patch_version }}


        
