name: pipeline
on:
 push: 
  branches:
    - main
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - run: npm install -g firebase-tools
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          architecture: x64
      - run: |
          cd hello_world 
          flutter pub get
          flutter test
          flutter build ipa --release --no-codesign
          cd build
          cd ios
          cd Release-iphoneos
          ls
          firebase appdistribution:distribute build/ios/ipa/app-release.ipa --debug --app 1:935264185763:ios:9e95a68fd95448bda7be16 --token "1//03K3eO7v7-fAnCgYIARAAGAMSNwF-L9IrYFixhx7UGwjiTmZjmd4_XcfMe9-DARDiiBre2szIBi3Xjr4GdbkNbHp1zfe2o1_3Ehs"
  #flutter build appbundle
  #firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab --debug --app "1:935264185763:android:c9373e09110f60cca7be16" --token "1//03K3eO7v7-fAnCgYIARAAGAMSNwF-L9IrYFixhx7UGwjiTmZjmd4_XcfMe9-DARDiiBre2szIBi3Xjr4GdbkNbHp1zfe2o1_3Ehs"


        
